# Generated by Django 5.2.6 on 2025-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='health_images/'),
        ),
    ]
