# Generated by Django 5.2.6 on 2025-10-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthrecord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='image',
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_records', to='health.userprofile'),
        ),
        migrations.CreateModel(
            name='SkinDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_images/')),
                ('bot_response', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skin_disease_records', to='health.userprofile')),
            ],
        ),
    ]
